### ISSUE TITLE
icon error?

### ISSUE THREAD

**Issue by deadadm1n** [Arvinth-Krishna/Reco-PC-Server#5]
C:\Users\Administrator>python C:\Users\Administrator\Desktop\Reco-PC-Server-main\reco.pyw
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Reco-PC-Server-main\reco.pyw", line 504, in <module>
    icon = iconSetup()
  File "C:\Users\Administrator\Desktop\Reco-PC-Server-main\reco.pyw", line 486, in iconSetup
    iconImage = Image.open("Reco_logo.png")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\PIL\Image.py", line 2975, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'Reco_logo.png'

**Comment by Arvinth-Krishna** [comment]
@deadadm1n Do you still have that issue?
